module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true,
  },
  parser: "@typescript-eslint/parser",
  plugins: ["@typescript-eslint"],
  extends: [
    "eslint:recommended",
    "plugin:prettier/recommended",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/eslint-recommended",
  ],
  rules: {
    "@typescript-eslint/no-prototype-builtins": "off",
    "@typescript-eslint/ban-ts-comment": "off",
    "@typescript-eslint/no-unused-vars": "error",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-non-null-assertion": "error",
    eqeqeq: "error",
    "no-console": "error",
    "react/display-name": "off",
    "react-hooks/rules-of-hooks": "error",
    "react/jsx-key": "error",
    "react-hooks/exhaustive-deps": "error",
    "@next/next/no-html-link-for-pages": "off",
    "react/no-children-prop": "error",
    "react/no-deprecated": "error",
    "jsx-a11y/role-has-required-aria-props": "off",
    "jsx-a11y/role-supports-aria-props": "off",
    "import/no-anonymous-default-export": "off",
    "jsx-a11y/alt-text": "off",
    "@next/next/no-img-element": "off",
    "jsx-a11y/anchor-is-valid": "off",
  },
};
